#ifndef PROGRAMINFO_H_INCLUDED
#define PROGRAMINFO_H_INCLUDED

#ifndef QT_STRINGIFY
#define QT_STRINGIFY2(x) #x
#define QT_STRINGIFY(x) QT_STRINGIFY2(x)
#endif

//Version
#define MAJORVERSION 2
#define MINORVERSION 0
#define PATCHVERSION 4
#define PROGRAMVERSION QT_STRINGIFY(MAJORVERSION.MINORVERSION.PATCHVERSION)
#define PROGRAMVERSION_NUMBER MAJORVERSION,MINORVERSION,PATCHVERSION

#endif // PROGRAMINFO_H_INCLUDED
