#ifndef VERSION_H_
#define VERSION_H_

#ifndef QT_STRINGIFY
#define QT_STRINGIFY2(x) #x
#define QT_STRINGIFY(x) QT_STRINGIFY2(x)
#endif

//Version
#define MAJORVERSION 2
#define MINORVERSION 3
#define PATCHVERSION 0
#define PROGRAMVERSION QT_STRINGIFY(MAJORVERSION.MINORVERSION.PATCHVERSION)
#define PROGRAMVERSION_NUMBER MAJORVERSION,MINORVERSION,PATCHVERSION
#define GUID "{C370AD59-EF9D-4DE1-B2F5-CD4D87123B11}"

#endif // VERSION_H_
